# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20e0276e5cdd743d5ae32f679d2ada9b6993e9c9cf8970b5f9ea382933b3e5e59ee18f0dd5890666b2547d4087c0b30e6d90bd14ba78836d951cf58299d3d767

test:
  secret_key_base: b09fe1132706ed9b648dfb671b17bfc544c0d76cbc64fdfe9160afa44118fdbaadba590fd011a5683fa568231355e97acece692edd24c1bc2af0702c286eb3b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
